apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - name: "9100"
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: node-exporter
  type: ClusterIP
status:
  loadBalancer: {}
