apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      # Current version found here:
      # https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/Chart.yaml#L5
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml
  # values:

