apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      # Current version found here:
      # https://artifacthub.io/packages/helm/metallb/metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 1m
  # Default values:
  # https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml
  # values:
