apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nvidia-device-plugin
      # Current version found here:
      # https://github.com/NVIDIA/k8s-device-plugin/blob/main/deployments/helm/nvidia-device-plugin/Chart.yamlA#L5
      version: "0.17.1"
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/NVIDIA/k8s-device-plugin/blob/main/deployments/helm/nvidia-device-plugin/values.yaml
  values:
    runtimeClassName: nvidia
