apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-public
  namespace: ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "3.34.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      interval: 5m
  values:
    controller:
      ingressClass: public
