apiVersion: v1
kind: Namespace
metadata:
  name: shinobi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shinobi
  name: shinobi
  namespace: shinobi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinobi
  template:
    metadata:
      labels:
        app: shinobi
    spec:
      containers:
        - image: shinobisystems/shinobi:dev
          name: shinobi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shinobi
  name: shinobi
  namespace: shinobi
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: shinobi
  type: LoadBalancer
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: shinobi
#   namespace: shinobi
# spec:
#   rules:
#     - host: shinobi.hoam.lan
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               serviceName: shinobi
#               servicePort: 80
