---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: drone
spec:
  releaseName: drone
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: drone
    version: 2.0.0-rc.10
  values:
    sourceControl.provider: github