apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snmp-exporter
  name: snmp-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
      - image: quay.io/prometheus/snmp-exporter:v0.15.0
        name: snmp-exporter
