apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmp-exporter
  name: snmp-exporter
  namespace: monitoring
spec:
  ports:
  - name: "9116"
    port: 9116
    protocol: TCP
    targetPort: 9116
  selector:
    app: snmp-exporter
  type: ClusterIP
