apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      # Current version found here:
      # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/Chart.yaml#L5
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
  values:
    sources:
      - ingress
    # Pihole only supports A/CNAME records so there is no mechanism to track ownership.
    # You don't need to set this flag, but if you leave it unset, you will receive warning
    # logs when ExternalDNS attempts to create TXT records.
    registry: noop
    provider:
      name: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://pihole-web.default
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        value: admin # temporary
