apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gpu-operator
      # Current version found here:
      # https://github.com/NVIDIA/gpu-operator/blob/master/versions.mk#L20
      version: 23.9.2
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/values.yaml
  # values:
