apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: metrics-server
      version: "3.12.2"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      reconcileStrategy: ChartVersion
  # Default values:
  # https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml
  values:
    # Specifies if the v1beta1.metrics.k8s.io API service should be created.
    apiService:
      create: true
      # Taking the easier option for now of just disabling TLS verification:
      # https://www.talos.dev/v1.9/kubernetes-guides/configuration/deploy-metrics-server/
      insecureSkipTLSVerify: true
