apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  releaseName: nfs-client-provisioner
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: nfs-client-provisioner
    version: 1.2.8
  values:
    storageClass:
      name: nfs
      provisionerName: ostrich
      defaultClass: true
    nfs:
      server: 10.1.1.2
      path: /mnt/tetons/kubernetes
