apiVersion: v1
data:
    TS_AUTHKEY: ENC[AES256_GCM,data:XJkASLGkbX1iP/znzm8m9bc+sWj/I8jYYGPurgNTIXZAF3UyxJxPTpsIkuGOGPbnhBzW25eH/L+XhH/7/Wyiop3Z1e7yaPqf0lGosf21KMveuTcx,iv:4eZZ9eMAkizfT1SIzGhdpjE0/jGCVZnYTcymXXtORK4=,tag:azw02tNkx9/UbH4WFysbzg==,type:str]
kind: Secret
metadata:
    name: tsidp-auth
    namespace: tailscale-idp
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Qk9lbWx0d3VJakhUeEJX
            NjNEVE83VVlWWlAwVTRKSlNXNDloZHdUcVE4ClY4L1FBVFVGdzFOWitXVVdVTm9h
            U245ckVaMmlxR1VnZ2tMbTZ2YW9Jck0KLS0tIHBpM2JsTkZVWVpnaUMrYUxnZnNj
            dkpaWjVPY3N2V1lTRXR3WkpOeHZ2VUEK4RG8oWuD/xI78sldwPCmnZsgsmoS6Awh
            2qAbB4holn1J7ASwVMAzi5wWZb5NYBJhFHTekRIO56zJskdAkZVcZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T00:16:12Z"
    mac: ENC[AES256_GCM,data:6A/7vSh1K0Sts1XdpP1/+0M1SsmSlYD9GhF2cmZDf5n86cIV6UR4UX+R7ILmf4GExUPmrea+5MI7La1hdj8fy0p161vbx4aiE6TDdh/oleIZs2CfXyPXd3AzIaBNxDm4o8Q4alz2z5+DPDUT3f0W1G62f8TDrelVG1xeqff20Ys=,iv:rDOYL1VCa6SDy3TSo7X3Nk6bEjdSWI3pE0trYbUiIqU=,tag:iMa/jhRWdJzXTE7957Egzg==,type:str]
    version: 3.13.0
