apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress-public
  namespace: ingress
spec:
  releaseName: nginx-ingress-public
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: nginx-ingress
    version: 1.26.2
  values:
    controller:
      ingressClass: public