---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prom
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 5.10.4
  values:
    prometheus.service.type: LoadBalancer
    serviceMonitorNamespaceSelector: {} # auto-discover all service monitors across all namespaces
    serviceMonitorSelector: {} # auto-discover all service monitors in namespaces configured above
