"""Render scripts/clef-omni/*.py into apps/clef-omni-scripts.yaml (ConfigMap mounted at /scripts).

The .py files are the source of truth; re-run this after editing them:  python3 scripts/clef-omni/render_configmap.py
"""
from pathlib import Path

here = Path(__file__).resolve().parent
files = sorted(p for p in here.glob("*.py") if p.name != "render_configmap.py")
out = ["# GENERATED by scripts/clef-omni/render_configmap.py from scripts/clef-omni/*.py. Do not edit by hand.",
       "# Clef-Omni quant / eval / serving scripts (issues #151 #152 #153), mounted at /scripts by the Clef jobs.",
       "---", "apiVersion: v1", "kind: ConfigMap", "metadata:", "  name: clef-omni-scripts", "  namespace: default", "data:"]
for p in files:
    out.append(f"  {p.name}: |")
    out += [("    " + line) if line.strip() else "" for line in p.read_text().splitlines()]
(here.parent.parent / "apps" / "clef-omni-scripts.yaml").write_text("\n".join(out) + "\n")
print("rendered", [p.name for p in files])
