apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxidized
  namespace: oxidized
  labels:
    app: oxidized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxidized
  template:
    spec:
      containers:
      - env:
        - name: CONFIG_RELOAD_INTERVAL
          value: "600"
        image: oxidized/oxidized:0.25.1
        name: oxidized
        ports:
        - containerPort: 8888
        volumeMounts:
        - mountPath: /root/.config/oxidized
          name: pv-oxidized
      restartPolicy: Always
      volumes:
      - name: pv-oxidized
        persistentVolumeClaim:
          claimName: pvc-oxidized
