---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oxidized
  name: oxidized
  namespace: oxidized
spec:
  ports:
  - name: "8888"
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: oxidized
  type: ClusterIP