apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: home-assistant
    version: 0.9.11
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: public
      hosts:
        - enomulous-birthday.tellus.space
    configurator:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: private
        hosts:
          - home-config.tellus.space