---
# Source: nfs-client-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.5
    heritage: Tiller
    release: release-name
  name: nfs-share
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ostrich
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "true"

---
# Source: nfs-client-provisioner/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.5
    heritage: Tiller
    release: release-name
  name: release-name-nfs-client-provisioner
---
# Source: nfs-client-provisioner/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.5
    heritage: Tiller
    release: release-name
  name: release-name-nfs-client-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]

---
# Source: nfs-client-provisioner/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.5
    heritage: Tiller
    release: release-name
  name: run-release-name-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: release-name-nfs-client-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: release-name-nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---
# Source: nfs-client-provisioner/templates/role.yaml

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.5
    heritage: Tiller
    release: release-name
  name: leader-locking-release-name-nfs-client-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
# Source: nfs-client-provisioner/templates/rolebinding.yaml

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.5
    heritage: Tiller
    release: release-name
  name: leader-locking-release-name-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: release-name-nfs-client-provisioner
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-release-name-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io

---
# Source: nfs-client-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.5
    heritage: Tiller
    release: release-name
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
      release: release-name
  template:
    metadata:
      annotations:
      labels:
        app: nfs-client-provisioner
        release: release-name
    spec:
      serviceAccountName: release-name-nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: "quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: ostrich
            - name: NFS_SERVER
              value: 10.1.1.2
            - name: NFS_PATH
              value: /mnt/tetons/kubernetes
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.1.1.2
            path: /mnt/tetons/kubernetes

---
# Source: nfs-client-provisioner/templates/persistentvolume.yaml

---
# Source: nfs-client-provisioner/templates/persistentvolumeclaim.yaml

---
# Source: nfs-client-provisioner/templates/podsecuritypolicy.yaml


