apiVersion: apps/v1
kind: Deployment
metadata:
  name: unms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unms
  template:
    metadata:
      labels:
        app: unms
    spec:
      containers:
        - name: unms
          image: ubnt/unms:2.4.156
          env:
            - name: UNMS_PG_PASSWORD
              value: baddabing
            - name: UNMS_PG_USER
              value: unms
            - name: UNMS_PG_DB
              value: unms
            - name: UNMS_PG_SCHEMA
              value: unms
            - name: UNMS_PG_HOST
              value: unms-postgres
            - name: UNMS_PG_PORT
              value: "5432"
            - name: UNMS_SIRIDB_HOST
              value: unms-siridb
            - name: UNMS_SIRIDB_PORT
              value: "9000"
            - name: UNMS_RABBITMQ_HOST
              value: unms-rabbitmq
            - name: UNMS_RABBITMQ_PORT
              value: "5672"
          resources:
            requests:
              memory: "1Gi"
              cpu: 10m
            limits:
              memory: "1Gi"
              cpu: 1000m
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: unms
  namespace: default
spec:
  selector:
    app: unms
  ports:
    - port: 80
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unms
  namespace: default
  labels:
    name: unms
spec:
  ingressClassName: private
  rules:
    - host: unms.hoam.lan
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: unms
                port:
                  number: 80
