apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'snmp-exporter (Fortigate)'
        static_configs:
          - targets: ['snmp-exporter:9116/snmp?target=10.1.1.1']
kind: ConfigMap
metadata:
  name: prometheus-cm
  namespace: monitoring
