apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'codelab-monitor'

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-cm
  namespace: monitoring
