apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: internal-fortinet
      protocol: layer2
      addresses:
      - 10.1.1.200-10.1.1.210