---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: unifi
    version: 0.4.1
  values: {}