---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: unifi
    version: 0.3.3
  values: {}