---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  releaseName: unifi
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: unifi
    version: 0.4.1
  values:
    timezone: "America/New York"
    ingress.enabled: true
    ingress.hosts: unifi.tellus.space
    ingress.annotations: 'kubernetes.io/ingress.class: "nginx"'
    unifiedService.enabled: true
    runAsRoot: true