apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matomo
        tier: mariadb
    spec:
      containers:
      - env:
        - name: MARIADB_DATABASE
          value: bitnami_matomo
        - name: MARIADB_USER
          value: bn_matomo
        - name: MARIADB_PASSWORD
          value: test-pass
        - name: MARIADB_ROOT_PASSWORD
          value: oh-hello-there
        image: bitnami/mariadb:latest
        name: mariadb
        volumeMounts:
        - mountPath: /bitnami
          name: matomo-mariadb-data
      restartPolicy: Always
      volumes:
      - name: matomo-mariadb-data
        persistentVolumeClaim:
          claimName: matomo-mariadb-data
