apiVersion: v1
kind: Service
metadata:
  name: matomo-app
  namespace: matomo
  labels:
    app: matomo
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  type: LoadBalancer
