apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:DRMNAej4/xZd92E3CJ5t3ZiNG67Krvqii4vQuXCVsdQEnPBj0LWF4bvEojgijXAxpA0ZEpQLZeUTVAL79MqVuRogJyA9LL6HMcfGDFeIrdnPLoEhQiR5eCnYSipzSKFrJHXQfCzFkUw=,iv:lpRJ1hJv0UZB4EzgbRb2yRzcWq2m8dx8xNLPCs5wmRc=,tag:f83w8xNwEGdFxEXe+XEwEg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0NuWd0izVYzgtx3cy6qER/q+Fz92mzNwIoIL6/Ze9LH9KnNcAOY7eA==,iv:uKMwF+83Nu768dnZXLF43wu9MW3ckSo62WUlIqgwxgc=,tag:whOoMSMauqoWMxFuBDfoYQ==,type:str]
kind: Secret
metadata:
    name: affine-secrets
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcWRkMnBSUTRhbitYRm8z
            VXFYMW83RGVZRURPdFdRZi80K2FMNVVqb2pNCis0RTZYNm5rb05BRzZxSEdtV0Fp
            WEZ0SU5PZUJGZlpOQ04rczkvNnVvTlkKLS0tIDBpQWhNaWc2WWN2ZEprVEpZK3Ro
            c1p4R1RIM2E4Vm40Nlp5bjk5OWVwaGMKwXnFHkOhH7oOCOqBDCuexphqQdzuEhKx
            SS5/ZH0ktcN0EJ5J8VYZJA7krobYVBltjXiOMzUoMgv6Jq9af5+wWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T13:22:44Z"
    mac: ENC[AES256_GCM,data:/ns8n5N9gPx/UEIEgwCJOwcDRmPxOsY4wj9sx4QwFaW3yQXKwoJLZVOuS0yQjfzBsuNruXV0Wk+USxG1bSNlvuhynd9i4cce+afvjsZJrxXZz2+RnIDBED4RcadgoAqY9ES2y0q1sj3Wb4db9GGDVs1pzZtWB05Zs8H3NJauFr0=,iv:4LVYg3X0kCY+5wnreezIt42BwDaemH/5XPHqlU7GgdU=,tag:WRFVJZOY5F0KDV+YWRh5KQ==,type:str]
    version: 3.13.0
