apiVersion: v1
data:
    config.json: ENC[AES256_GCM,data:6WCdgXqmcRkzmZtIBPpufslDs/mFKQWGPc4LbZld5faR20HJ+P5/AYxxGqKvd6v72wKL7Cas+szuYTPD3YFi0s9ACm1TPNuR7LAn0hIqbCicqtEVxtTLqOD30r69QqJu3dYUddCP7LeEOpeV1wRGi0G24TzrF9BNlgHSxosbDBTCja9FwZ7qzALaIOG47IKkloojCbd3hdgZeN5K0GZiLN2EXHKoCXOZlLYvd8qWuYAs+6ix08qRFMGMfPJMljbz1eBWXFRcuOnJmH4kq6YuxOFndFWwdgaLdLe+ZRUDxL9HrU5T1HRNVp3cc+izDc6l4xWvqJUU12LA5mn/h3uMaWWG2ulXUzru8Mq4xSfIDTEAnaYiUbotOMxlcTykw5RVHk8EIYSK6/Ks9WRftpBxydgvcd8lZudQwRU90f5F5EoEEWrenoh5kmi0gpqz8MNRS3n0lYLiq/lJj1MS4vnAYSiJOi26Wv+6B9pifYFziIKe4V73NpeUKG20RCn1wqaQdWCUvztk92ZRRoHwyT/lzQJzEML+JBfS0zpa1ekYyr8YDH4q+Eu8Ervn+1mHZriwKFLKwJAZyvE4jlBKmLSWG+sldng/H1MkAAKJuIqfX4d9mAf+HXRHeZgwWEe+65OYo6tkVmaWB/VxUqftReD+mBFkJs2sYRctqKfOT8twLuejow9gEoIT+W34v8ZCu5I8IMKD3hxYxhHUEe3+h/XhKPf5MG+La7Pqh0RqYLVnS5VXv+9S1ySW1sKinKIZL7T8JJnstWdWXO+7rGL5XtFbnKJrIaiSH5C+4GKi0TDBr99hGCIuZSBsXKlp0q/9aB4aWCMllpwnA0lJ+MKfJi119tvGzjsztK1FnMOLWECgUYy+ufkR6ebAPSsK7toMmIHGH4/ofPsCfAHyCLIXlSp+mE2YwG9PdI/MwmSaSLnXHypFPhTSU6fxRNt7kVaa2f/6iLRIeWoBWHm9i7AxVB0NadbSpKhrs3Z4REH0iNmcRkYg4JETvB93nQrXQ+ZgLjWwcHyZ4o7GKLJxDArY2WK87DEm9+rPkvxGVYC/oV51HK+PuTqpVeJN1AU2Q1fsJVV67iEZP94Yv7JLsohrHet/7XW8W2c50GN0OuDFznZco6JJxMCBrbWXniFZf6S1OL/8PCwN4D6yDV+zOCD9hZ6eBAGhuEBCuaMnFV7HiUzs1z9PNO6Io2aWZImSxEW8/aSr,iv:ugqCKvhAKbM8iZ0VaB464YvNQ4TDzA6SBIinRE334LA=,tag:4rofGANccWNIP3E8AhKbZw==,type:str]
kind: Secret
metadata:
    name: affine-config
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4N09WeVpsLzRIRXhNQ3dv
            NGQ3T1VwWm9mMDVRd1JqVmZIeTlIWVRUZ1Y4CmVuT2VweGh5NTFUWkxsWGVpVERB
            Y3dhUUNBVlJiRHFYeDRVZTFMTWxzZTAKLS0tIFR3TjdVc0RoT0U3Q2NFOHF4WUt0
            cTBPbko0OHRRRHR2OWp0OHdQU3BMZkEKJxetmsPwzBPIbwAePJqH0mDKJWsXt5J2
            TTaJVJFCIe3GTn2zXO4OLcf6thGJ7scikAKrdbpYiOKLrRIp3ySySQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T03:24:03Z"
    mac: ENC[AES256_GCM,data:UlpFOlJhF6xYtcKNXMEEXfpSXayuDZNAE75GdIOG24QXr87XFU+8KSBOmi810YzxyIFawYEMFvBhv0NVFFTj//1koPHvRvSl7X8nJYtnywt9Tkh2inTBrhzWHjPpi3NygE9r4mGm+rlKO1i/YvSD+r+WS5C5mbr63hwRClP8VSw=,iv:HDprWvoLM6z4tsxp2LSLP3qqI9bWIC8N4XFgS8oCadc=,tag:16cKGLToFEL2hneWi/hlqQ==,type:str]
    version: 3.13.3
