apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: archivebox
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: archivebox
      # Current version found here:
      # https://github.com/truecharts/charts/blob/master/charts/stable/archivebox/Chart.yaml#L38
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: archivebox
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/truecharts/charts/blob/master/charts/stable/archivebox/values.yaml
  # https://truecharts.org/common
  values:
    ingress:
      main:
        enabled: true
        primary: true
        # annotations:
        #   cert-manager.io/cluster-issuer: letsencrypt-staging
        ingressClassName: private
        hosts:
          - host: archivebox.hoam.lan
        # tls:
        #   - hosts:
        #       - jellyfin.hoam.lan
        #     certificateIssuer: letsencrypt-staging

    # persistence:
    #   config:
    #     storageClass: nfs
