apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: flood
      # Current version found here:
      # https://github.com/truecharts/public/blob/master/charts/stable/flood/Chart.yaml#L38
      version: 15.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/truecharts/public/blob/master/charts/stable/flood/values.yaml
  values:
    # Super minimal configuration to avoid any template issues
    ingress:
      main:
        enabled: false
    
    # Just configure the basic service
    service:
      main:
        enabled: true
        primary: true
        type: ClusterIP
        ports:
          main:
            port: 80
            targetPort: 3000
    
    # Empty objects for problematic sections
    global: {}
    ingressMiddlewares: {}
    metrics:
      main:
        enabled: false
---
# Create a separate ingress resource directly
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flood
  namespace: default
spec:
  ingressClassName: private
  rules:
    - host: flood.hoam.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flood
                port:
                  number: 80
