apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: flood
      # Current version found here:
      # https://github.com/truecharts/public/blob/master/charts/stable/flood/Chart.yaml#L38
      version: 15.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/truecharts/public/blob/master/charts/stable/flood/values.yaml
  values:
    # Completely disable all Traefik integrations
    ingressMiddlewares:
      traefik:
        tc-basic-secure-headers:
          enabled: false
    
    global:
      traefik:
        # Disable service annotations from Traefik
        addServiceAnnotations: false
        # Disable common middlewares completely
        commonMiddlewares: []
        
    ingress:
      main:
        enabled: true
        ingressClassName: private
        hosts:
          - host: flood.hoam.lan
            paths:
              - path: /
                pathType: Prefix
