apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: flood
      # Current version found here:
      # https://github.com/truecharts/public/blob/master/charts/stable/flood/Chart.yaml#L38
      version: 15.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/truecharts/public/blob/master/charts/stable/flood/values.yaml
  values:
    # Enable ingress but disable Traefik integrations
    ingress:
      main:
        enabled: true
        ingressClassName: private
        hosts:
          - host: flood.hoam.lan
            paths:
              - path: /
                pathType: Prefix
        # This bypasses the Traefik middleware integration
        useTraefik: false
        annotations:
          # This prevents Traefik CRD lookup
          "traefik.enabled": "false"
    
    # Disable all middlewares
    ingressMiddlewares: {}
    
    # Globally disable Traefik
    global:
      traefik:
        enabled: false
        addServiceAnnotations: false
        commonMiddlewares: []
      annotations: {}
      labels: {}
      
    # Disable any potential Gateway API routes
    route:
      main:
        enabled: false
