apiVersion: v1
data:
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:WIkcW1haXQxA62OL,iv:QrgGsT3/m3pjNyknG5bL2CysxXT0uFYdPaG8va+mGPY=,tag:slqk4hGCWxSz1zKMrSr6Gw==,type:str]
kind: Secret
metadata:
    name: frigate-rtsp-credentials
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNyt3Q0dTQWpuK0NPbVBx
            TWgxa3Y5STJzRlc3NmhDNXVBWWdpbFV6MEhvCnRRei8rZFIyMG1XU1BuMXRqU2VK
            aVBZdmpZUGk4QXplNVpwVW5wL1JEOGcKLS0tIFZKQ281YXA3OERaT0w1SzJTd0FH
            RS9NVTh4QnRuVkJEYTZncDlKaHB0YjQKeS8NoRJ+HvGcHYcstre3PKKCkDEJ1Lm2
            ADryBkzb63HFsK3GoMxk3Zx7INioMfdgORk825MKB0oG2dVfj+VSaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T01:24:42Z"
    mac: ENC[AES256_GCM,data:C8iJjzpR9CaUpRrJ5VrjmxnknLOWwExTmPg4htfwCcW7WjZhV6MNlRfz3GLCMaoYE5WWSE6HR3ePlCaYzPeTF2Ciw7aqTTCLncFhK5Jaa+AAGhkgX1p8MeSCamkcDAJTR96E6C0Rvnln/vWxY4rzvIHajP7g6mgEB8MbzWr9yys=,iv:7cluhyshGAyGnB5xlEbfeOiZ5LsOapztOWVo/0FJgN4=,tag:vQHlBjo6Q1095l20BNjh4Q==,type:str]
    version: 3.13.0
