apiVersion: v1
data:
    HANDY_MASTER_SECRET: ENC[AES256_GCM,data:QXQqmCh1RV5r+ayXVqurxnaR/+8uE/XV1LNxiBwrMbqymiRCJZ4G9caAFcksC0uXQ74ZL0zldU7PrH/hjxD+oKo4Ql0QypWz5tNTyv8nbk9lNvvhH2o1rw==,iv:eiq2+TUTz0yhNSded8EQXCjPj+353YiCDbhkVMUHCL4=,tag:1q+u36qmdo9RTY7tMxVcZA==,type:str]
kind: Secret
metadata:
    name: happier-secrets
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcDkrUHRUQjJjT2dEVkdo
            bEdLMTRpalVvMWlHMGc2bHJXZkxNMENjeVdnCkJTSnc2a09PQUVnQndFVTVVMmVI
            eHlGb2tMWjRWc3JUU2ZaczBjN3pOSm8KLS0tIG1XYjVFakRVM2xnZHl4WDArTWQw
            dTk3Z1c5d2hZTW5IeFZ4ZkdjMGJLZXMKv1foFmgGV95MpduMDMM9Xz8nFTt/Vvri
            s/motEcf5uKWZrDbE5dQwo88OC2PI6Pvg8a/bCk5OYrjQWpfi3n4cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T05:57:27Z"
    mac: ENC[AES256_GCM,data:u5u/pRhAIwHUXis5VV6zS5LaX4SjWKTUBimoRi5MRwKyh2o1xcZnlWhevwfLJ3USv2NU7K+xBg1n0KOYFApkeodaMCWWCc3fzm9J2Ns5bVuHYSK0RBLjiIbUPWZlY8N614Hsj8c1SYOjPozlI2KwMNjm6pOZd9kFti+X68UBvt8=,iv:ic8CdgzfeIFnTwaDj651auZD6hOWgBXO1AdUK9RflnE=,tag:OwNoiabTXXB3X/uUhzoNAQ==,type:str]
    version: 3.13.0
