apiVersion: v1
kind: Namespace
metadata:
  name: happy-server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: happy-server
  namespace: happy-server
spec:
  interval: 5m
  chart:
    spec:
      chart: happy-server
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: happy-server
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/dbirks/happy-server
      tag: "0.1.0"

    replicaCount: 2

    # Use bundled PostgreSQL and Redis
    # NOTE: Persistence disabled until NFS server (ostrich) is back online
    # NOTE: Using default Bitnami images (not Alpine) - Alpine has permission issues with emptyDir
    postgresql:
      enabled: true
      auth:
        database: happy_server
        username: happy_server
      primary:
        persistence:
          enabled: false  # Disabled - NFS server offline

    redis:
      enabled: true
      master:
        persistence:
          enabled: false  # Disabled - NFS server offline

    # MinIO for S3-compatible storage
    minio:
      enabled: true
      auth:
        rootUser: admin
        rootPassword: changeme-in-production
      persistence:
        enabled: false  # Disabled - NFS server offline
      defaultBuckets: "happy"

    # Resource limits
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
