apiVersion: v1
kind: Namespace
metadata:
  name: happy-server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: happy-server
  namespace: happy-server
spec:
  interval: 5m
  chart:
    spec:
      chart: happy-server
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: happy-server
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/dbirks/happy-server
      tag: "0.1.0"

    replicaCount: 2

    # ============================================================================
    # Subcharts configured with emptyDir (ephemeral storage for learning/testing)
    # ============================================================================
    # Data will be lost on pod restart - this is for development/learning only
    # When NFS server is restored, set persistence.enabled: true for each

    postgresql:
      enabled: true
      auth:
        database: happy_server
        username: happy_server
      primary:
        persistence:
          enabled: false  # Uses emptyDir - data is ephemeral
        # Fix permission issues with emptyDir
        containerSecurityContext:
          enabled: true
          runAsUser: 1001
          runAsNonRoot: true
          readOnlyRootFilesystem: false  # Disabled for emptyDir compatibility
      volumePermissions:
        enabled: false  # Not needed with emptyDir

    redis:
      enabled: true
      auth:
        enabled: false  # Disabled for development
      master:
        persistence:
          enabled: false  # Uses emptyDir - data is ephemeral
      replica:
        persistence:
          enabled: false
      # Disable Redis-level persistence (AOF and RDB)
      commonConfiguration: |-
        appendonly no
        save ""

    minio:
      enabled: true
      mode: standalone
      # Use official MinIO image (Bitnami image unavailable due to registry changes)
      image:
        registry: docker.io
        repository: minio/minio
        tag: latest
      auth:
        rootUser: minio-admin
        rootPassword: minio-dev-password
      persistence:
        enabled: false  # Uses emptyDir - data is ephemeral
      # Use defaultBuckets (provisioning may not work with official image)
      defaultBuckets: "happy"
      # Security contexts for emptyDir
      podSecurityContext:
        enabled: true
        fsGroup: 1001
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsNonRoot: true
        readOnlyRootFilesystem: false  # Disabled for compatibility
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 250m

    # Resource limits
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
