apiVersion: v1
kind: Namespace
metadata:
  name: happy-server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: happy-server
  namespace: happy-server
spec:
  interval: 5m
  chart:
    spec:
      chart: happy-server
      version: "0.1.4"
      sourceRef:
        kind: HelmRepository
        name: happy-server
        namespace: flux-system
      interval: 1m
  values:
    # Allow non-Bitnami images (for MinIO official image)
    global:
      security:
        allowInsecureImages: true

    image:
      repository: ghcr.io/dbirks/happy-server
      tag: "0.1.0"

    replicaCount: 2

    # ============================================================================
    # Subcharts configured with emptyDir (ephemeral storage for learning/testing)
    # ============================================================================
    # Data will be lost on pod restart - this is for development/learning only
    # When NFS server is restored, set persistence.enabled: true for each

    postgresql:
      enabled: true
      auth:
        database: happy_server
        username: happy_server
      primary:
        persistence:
          enabled: false  # Uses emptyDir - data is ephemeral
        # Disable security contexts entirely for development/emptyDir compatibility
        podSecurityContext:
          enabled: false
        containerSecurityContext:
          enabled: false
      volumePermissions:
        enabled: false  # Not needed with emptyDir

    redis:
      enabled: true
      # Use Bitnami image (Alpine has compatibility issues with Bitnami chart)
      image:
        registry: docker.io
        repository: bitnami/redis
        tag: latest
      auth:
        enabled: false  # Disabled for development
      master:
        persistence:
          enabled: false  # Uses emptyDir - data is ephemeral
        # Disable security contexts for emptyDir compatibility
        podSecurityContext:
          enabled: false
        containerSecurityContext:
          enabled: false
      replica:
        persistence:
          enabled: false
      # Disable Redis-level persistence (AOF and RDB)
      commonConfiguration: |-
        appendonly no
        save ""

    minio:
      enabled: true

    # Resource limits
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
