apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: happy-little-claude-coders
  namespace: default
spec:
  interval: 5m
  timeout: 15m  # Increase timeout to handle slow installs
  maxHistory: 3  # Limit ConfigMap bloat from release history
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  chart:
    spec:
      chart: happy-little-claude-coders
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: happy-little-claude-coders
        namespace: flux-system
      interval: 5m
  # Chart values reference:
  # https://github.com/dbirks/happy-little-claude-coders/blob/main/chart/happy-little-claude-coders/values.yaml
  values:
    image:
      repository: ghcr.io/dbirks/happy-little-claude-coders
      tag: "0.12.1"

    # Multiple workspaces - each gets its own deployment/pods
    workspaces:
      - name: cawcaw
        repos:
          - "https://github.com/dbirks/cawcaw.git"
        storageSize: 5Gi
        persistent: false  # Using emptyDir until NFS is restored
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi

      - name: librechat
        repos:
          - "https://github.com/dbirks/librechat.git"
        storageSize: 10Gi
        persistent: false  # Using emptyDir until NFS is restored
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi

    # Global git configuration
    git:
      userName: "David Birks"
      userEmail: "david@birks.dev"

    # GitHub authentication via GitHub App
    githubApp:
      enabled: true
      secretName: github-app-credentials
      refreshIntervalMinutes: 50
      sidecarImage: ghcr.io/dbirks/github-token-sidecar:3819e0c

    # Claude Code authentication
    claude:
      secretName: claude-oauth

    # Happy CLI config - using per-workspace PVCs
    # NOTE: Requires persistent: true on workspaces AND working storage class
    happy:
      sharedConfig: false
      perWorkspaceConfig: true
      configStorageClass: ""  # Use default (currently nfs - needs fixing!)
