apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      # Current version found here:
      # https://github.com/pajikos/home-assistant-helm-chart/blob/main/charts/home-assistant/Chart.yaml#L20
      version: 0.2.60
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/pajikos/home-assistant-helm-chart/blob/main/charts/home-assistant/values.yaml
  # values:
