apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: invidious
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: invidious
      # Current version found here:
      # https://github.com/truecharts/public/blob/master/charts/stable/invidious/Chart.yaml#L41
      version: 11.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/truecharts/public/blob/master/charts/stable/invidious/values.yaml
  values:
    cnpg:
      main:
        enabled: false

    # Add ingress configuration
    ingress:
      main:
        enabled: true
        ingressClassName: private
        hosts:
          - host: invidious.hoam.lan
            paths:
              - path: /
                pathType: Prefix
