apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin
      # Current version found here:
      # https://github.com/truecharts/charts/blob/master/charts/stable/jellyfin/Chart.yaml#L39
      version: 18.8.15
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/truecharts/charts/blob/master/charts/stable/jellyfin/values.yaml
  # https://truecharts.org/common
  values:
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        ingressClassName: private
        hosts:
          - host: jellyfin.hoam.lan
