apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: librechat
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: librechat
      # Current version found here:
      # https://github.com/bat-bs/helm-charts/blob/main/charts/librechat/Chart.yaml#L17
      version: 1.8.7
      sourceRef:
        kind: HelmRepository
        name: blue-atlas
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/bat-bs/helm-charts/blob/main/charts/librechat/values.yaml
  values:
    librechat:
      configEnv:
        ALLOW_REGISTRATION: "true"
        OPENAI_MODELS: gpt-4o,gpt-4o-mini,o1-mini,o1,o3-mini,o3-mini-high

    ingress:
      enabled: true
      className: private
      hosts:
        - host: librechat.hoam.lan
          paths:
            - path: /
              pathType: Prefix

    image:
      registry: ghcr.io
      repository: danny-avila/librechat
      pullPolicy: IfNotPresent
      tag: v0.7.7-rc1
