apiVersion: v1
data:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:mekGkhs0t5fs0D0RQ1AMprW2PjsEeC9WFMf4E3OrKbXBPjsF9D01PqD4350X+3fJ,iv:WPCvoUGS263HN1FxT3jM26viAVW/OWNGWbXWTb093BA=,tag:8tAz3c5GeEhRoeXXZm2uHw==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:8VMJgg2TTThYJsqiN9ze6FZxQtlYe0+V/Nqat+aHeUtRIhXSsJdXWeCVgVrSfXXVGgyQAI9qpFA=,iv:WKgwtZG0Ecf62w9Gq98iMR9W9BuA87hkHA/8HhOXS3I=,tag:GoIeNIErj6Fk8Ta6eHDJnQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:wUlLctKeg+dJo4A0LXk3EV/RBWL9QIIZN3aqgPmyZ9iwkhLA2TGHzUZ0RB8FhDFykeZlvqtaf0ptUltB,iv:0Sosj29kfT3USNDcIrxOC6UDRiyOdYDpZA5SFeqxCao=,tag:cjuORBey/3rC/ymvvSL9IQ==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: llm-grafana
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabU9hSVdQR0RVTGRLQkM0
            YUNsZXpTZjU1UG1IUWo5cFZpWTFVVzk4NVVvCkg2MVEyQ2UycThMZThORDVidThB
            V2Y2TisxMkNlTkN1M1dLRThNb0wwZ00KLS0tIHpycCtEbzE1SEg1aUxUMkZ5WDhH
            NWFabHFodkE3aC9uZUNoemgrYjJpM00Kjc3i7mltWMv6l2JLmnuHCGXX4zjJOK0m
            W+peVVPlJ6xVgpAa3sYgbxxiNNyiDU6OsIqeuEkX/Q1Sryhg/fTIkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T03:17:43Z"
    mac: ENC[AES256_GCM,data:kJB4YIeTnQTAvOwLuI9vv/q7S2+TYjupXv7kYb8YCmGWoznVt8/CY66VXe3+jDaCU6XmX5oLXVWxZx7E+M+lNpf69rIYLcGPlVDVFpTEXc4pZCFgjNBaDGQ+RTm3JBcQMqLhbI/bC1lMan4w+NwrLwRpS2gAOYZXLbew3NeMUZg=,iv:H6/IiyU7ghL5vOeI4ZyGU+raprEP04S3MTTynMHxT+E=,tag:Y75+aJ3R9xiSyE1XHHtO5A==,type:str]
    version: 3.13.0
