apiVersion: v1
data:
    MARKET_AGENT_ALPACA_API_KEY: ENC[AES256_GCM,data:XDuOBaQLNph39ZOdgBhVO2U+USsr6+2P2wX4kQ+Y2Y34AdWU,iv:uhI/na9vmoM6udjluhpnkao+UCoGlpPm62LkAk1bTuw=,tag:mqAeydpvZvvPEgMRE823Qg==,type:str]
    MARKET_AGENT_ALPACA_SECRET_KEY: ENC[AES256_GCM,data:Bt5ipRYppZIBKgZsYX4iFQOIH8F18pzgufUMopR5i88gB7JWf8ifZ6SpRDQEvDZ8K6myJ5CQSHHIWNqq,iv:0HNcrrxn1XiMzOce0WX4cVVmz2BrvkXBjozBqHifY2k=,tag:lghzT6AOq711foGkp6puNQ==,type:str]
    MARKET_AGENT_BROKER_MODE: ENC[AES256_GCM,data:XLlyNNjy2jI=,iv:auj4UFG5i98hpI4mZJJeGnLj0+OWvmMBddgCVQtB6b8=,tag:Cr73KeEO+L5lBCJl6nEG7Q==,type:str]
kind: Secret
metadata:
    name: market-agent-broker-secrets
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbW9uUjlhRnlsL0o5MnJK
            dFhVWVExb1A0dTBjRXE5SEtnSWs3emRKaW00Clc1WndvUi95a1VDSEhISUJRV0Jj
            L0VQVDdtRUM5MlFiellhbWUxZzhUd2sKLS0tIElkN3ZaaW9JQ1VLbmh5OThwOWFt
            L1ViVFcrKzNzbUdQdHdUUWN2aFBJWm8K5qZwyUYGteK7yvhm0OyQrFS5bzNntE2i
            8U4jRkdo/a1CGkSJ3XfaovkEV9wOiLOCOXquc/aWJ0ua519vw/+YfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T05:36:47Z"
    mac: ENC[AES256_GCM,data:HleQhKYmGNGIjjGt3eyrNS9n5H+00RArZ8VxNqfRWwbvYHsnjDgWA5f2PsyFKRvavOE+72hx1+zDXJmMFCC7u4rkgk6VawL8ICYV6NLIuAEakP61BDmobgibYVlC0y5SKOk22cPip31Pnn1VhjzNmekgrZAa9w6j8gBB9WqLYZY=,iv:Wg1GmjS8b39U0ZTCumikSgOHfJ8si8CQbWuumIKBZ+Y=,tag:j/eAsr6A4E6b/7Cuf/9jDQ==,type:str]
    version: 3.13.0
