apiVersion: v1
data:
    MARKET_AGENT_ALPACA_API_KEY: ENC[AES256_GCM,data:8wRDNwN0aJPm6SXprRDgKA1a+ZdQTaKsHOpi1OE7mLd9p/R5,iv:aG2wmNrX97i3HJ954s4lr5UAo72eXEG3U1S2LrrZ61Q=,tag:BZ01QrrPnQL9wojjkeyGBQ==,type:str]
    MARKET_AGENT_ALPACA_SECRET_KEY: ENC[AES256_GCM,data:NX3uAwN7ykO9qywZncyWupm3FKkDpu0DpifUKImZMV6jWGYWnUeYgx/R8GNCKDAZiVS09Uk45wOf+UkY,iv:NCk8XtzCc6ub4/MsHYuVrEPu6RliCuh2wgitZrOCt0w=,tag:XmeDxCTU3dScNmayoul7qw==,type:str]
    MARKET_AGENT_BROKER_MODE: ENC[AES256_GCM,data:V8c+cFm9N8Q=,iv:V2zE2Pya4O30ran7nCkbMCn9+rRY/KfzTiYV06zWspk=,tag:xV8D1G7e1E+uBMrLIiSZZw==,type:str]
kind: Secret
metadata:
    name: market-agent-broker-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNExlSEJESjNBOC9QSHlv
            bTVOSXZKNmpyMjVBNGJwZlJEYVQ2TVpyN2xJCjdSK2p1NkorS0d0c1pqSlJJbGRR
            K3JTbDZVTlR0UENCY1EydThpZjlNTW8KLS0tIDRtUVdGUC9OaEVKR2dOcmNOU3l4
            ZjFxMGdvOTZmc2JwdE83WXM4UzdQN0UKbrhee4xw27Z2CnOzD3YjIRczroBEM7bK
            VKFQoLTvyGagsia6qcQsf+ti2a0TU7K8SAqUTdw0dtdyTfZi5Ysw1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T05:29:18Z"
    mac: ENC[AES256_GCM,data:SdCZPeGLgCkMQb9hgLcJkueWrCAmpF6DS+M1De2knybQ8246QEhjuGK9UM2VPraQYY9KMWLb3TgixVOaGkU6XkxQ4pftYHJJAzxtxX7afRVTxo+Gde/zEue/Z/AIhUU5uP5TKNNUJUgRnnlt2G4iRLoVdHQf5F8uU5YSTTZd1MM=,iv:DNIwAlQmLwEDCAfVE0jFA1RU0rewqTxZ/NOFibGzLD8=,tag:onJw6iS9ZUN+W3Vu2qnGjQ==,type:str]
    version: 3.13.0
