apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      # Current version found here:
      # https://artifacthub.io/packages/helm/metallb/metallb
      version: 0.14.5
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 1m
  # Default values:
  # https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml
  # values:
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: kube-system
spec:
  addresses:
    - 10.0.0.200-10.0.0.205
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-advertisement
  namespace: kube-system
