apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      # Current version found here:
      # https://github.com/8gears/n8n-helm-chart/blob/main/charts/n8n/Chart.yaml#L3
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: 8gears
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/8gears/n8n-helm-chart/blob/main/charts/n8n/values.yaml
  values:
    ingress:
      enabled: true
      className: private
      hosts:
        - host: n8n.hoam.lan
