apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: otwld
  namespace: flux-system
spec:
  interval: 1h
  url: https://otwld.github.io/ollama-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: default
  chart:
    spec:
      chart: ollama
      # Current version found here:
      # https://github.com/otwld/ollama-helm/blob/main/Chart.yaml#L7
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: otwld
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/otwld/ollama-helm/blob/main/values.yaml
  values:
    ollama:
      gpu:
        enabled: true
        type: nvidia
        number: 1
      # models:
      #   - llama3
