apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ollama
      # Current version found here:
      # https://github.com/otwld/ollama-helm/blob/main/Chart.yaml#L7
      version: 0.43.0
      sourceRef:
        kind: HelmRepository
        name: otwld
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/otwld/ollama-helm/blob/main/values.yaml
  values:
    ollama:
      gpu:
        enabled: true
        type: nvidia
        number: 1

    runtimeClassName: nvidia

    # resources:
    #   requests:
    #     # nvidia.com/gpu: 1
    #     memory: 128Mi
    #     cpu: 10m
    #   limits:
    #     nvidia.com/gpu: 1
    #     memory: 4Gi
    #     cpu: 2000m

    ingress:
      enabled: true
      className: private
      hosts:
        - host: ollama.hoam.lan
          paths:
            - path: /
              pathType: Prefix

    persistentVolume:
      enabled: true
      size: 70Gi
