apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:N7vGoiKXvv6Bq6hfuWrvnZyuIz8dpJUgujbDWnA5O9J5pjVYHJHo35NNetZgCx8kuDOiLn4xsQZM7ZIOIvGm0TEL2g6eeUxmnMhc19IjE69e9vpg7+mSL3nzukHDf4xovDitr1ELCzl8gIm8z70bbkm98PJGQVSgoef3MgYAFwoNkOR21jMumO+RVg+YUPuw4x9onCJk0+ShzRYaRMPc1B174jrKvk3eYT02Eg==,iv:/ro7HRTpT6TqCF6nV5CpuFUEic2+jYEhvsQRhGKWFSI=,tag:lXvdtdtlt3LSjs7Tt9x9Dw==,type:str]
    OMNIGENT_ACCOUNTS_COOKIE_SECRET: ENC[AES256_GCM,data:g1FvsIUX5YsfoQbyLZfvph5HJ32X4uIOr0C1PW6CInaBkqcvsum0CfY91SDX+e1vRGOlxcwqI4J1cmQMzX1/nVpxu/glR2saJZKAlFX41UwzVwqXd4MsVQ==,iv:kaHWZuwKhOtpXW4gueS/xFnk8EeNhlVisBlUmAgHMEU=,tag:k1Q3ylEiiYOOegccNP7xmg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:saMiNGlfYC5EghA96+Ba9Vraj4kjDV8ZlEinvHcWdNYFB38lG1PSluD/MzZTW87pYOYOVLtgFpNjJL2aFSu1PA==,iv:LexO53U3Zo3otxferZRfKCpSiqK/hlVE45oCk3+G0FU=,tag:5g6RenUMjVtNQbSXnRlQPw==,type:str]
kind: Secret
metadata:
    name: omnigent-secrets
    namespace: omnigent
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSG5qN1RoZXVSa2hleklT
            VEpYdDFsem1sTFpUcWVJdXY4M2NjQkd1VEIwClB3VzFQVWRZcWkvZDdMUGtGMUNP
            K2RUd3IvN01lNHBndDhFYWYzUW40NzQKLS0tIHI0UnVESVYxVmJjN3JNVld4OTFE
            blU0Vlp5SGU1QjJMdk0zcXY2ZS9TUlUKBR5f49RJva+rNSd/4BmsuR626O0J/kpw
            bn2EiuDNwtq4snCbG5TtzSxqMOoPvgX7dy62+WfYKQvd6cVkLbEoqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T14:32:28Z"
    mac: ENC[AES256_GCM,data:uaiaLUM7+W/rYHCUE6dRT9xPdxQfIqK2DudpLdOdjZQGbfkgKQ2UU37HIdcSlsTSot97an2cYfB0iCOgGGFgiQ/mmi+O4s1YEPwh88k5rAyUahnnXhsWB5UPsPqHKiUimh71OacFkwE1KJB+N9cfxQ60NFQnygwfXHc9N7VoaSA=,iv:s1gKY3sSYJRRyjfJJ03yWfynTBforpyzRsms3oHh018=,tag:MmRDsePFUH2fDbLs8tYKpQ==,type:str]
    version: 3.13.0
