apiVersion: v1
data:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:gTm5EeglYEhvq6OMtdDBoowJADyil6+LxM8nEIvd58bmxUqwODIA9KzI4yRYjwkj90lHcRoaajiXqBzAxtGCZ8kS4oQABGdrKO2+B9LnN8A2d6KA/h76iPVWwCHPgtB0vlQhgHeH1VOd5HJnJ26xCr2taQWLNDyitLe6Xg==,iv:VoxD9zBEzAL0cr1zWyjBh1cpWZtiX9DLumdRSL3h2EQ=,tag:DjrzcDdWtfs4tbJiZdDoKg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:RwMP4eFSoGdUwi/G2ZXhrXMo7EDuEjFS2VXdKnpf0fPSqYfh9hJpnYg28iaeQq4EsfP6Cv4BP/WShNXjB/BrK0T33Y1vmlWw6p3tWVeqiMA4Dat7B9mQkeGFpVu2L7Xu8usYETkcOZi8K1TYWB9emjYPohS1rnnrJjZOTQ==,iv:Lo8uSJR8Jl6CNpR7JD1GVE05z4VbJ7I4BlPB4iaRi5Y=,tag:o5DE0N4zVErhn9ACBaFWYw==,type:str]
kind: Secret
metadata:
    name: omnigent-creds
    namespace: omnigent-sandboxes
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYmlxd2p5RnJuRCtwWkZI
            L2l2ZStnRzlvZGtFYUgrazJYR0dab3RQM3lZCjR4L0trQXpVWUpod2dTZ0RGRHBs
            WktWZThEQTVkdGIwNDFCczhERlBKUGsKLS0tIE9LTW8zd0VORmRKZ2lzZ2MzMVAv
            QjN4M2pTTFJYN1JmZTl6N1dXSGlRTEEKzZBqPns44QJLSjH7DyRl6VFAYqaMy3ut
            K2IE8wHTa2P3WPv118+38N8lje3vADxZOjGpJ17/c5Pg2XB1fBGfLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T19:50:38Z"
    mac: ENC[AES256_GCM,data:QgVEqNJuE70Li2N7tSmK2etXGRTzSPco4+pcGcfWczjFZkAQGPMrhwoc+biEq6iqh4XP74dHhXEPxFXkmjS4f1AFWYHIHYvxMD4mKiH2fdYNJe/RwoZZm451ymfI9IKvIbaMKH7y31/SdwjKXLhBQ8USHrwhFebHeL1DuagzLZg=,iv:Wxd8Yol1nSRVjTchRXgHkudQCxFuGd/9FnrnNt1BD0M=,tag:IEbzaPETVZgXHvr6jtFz6Q==,type:str]
    version: 3.13.1
