apiVersion: v1
data:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:B4LiD9F9Za4Qa2wdweJ5LnxDof1PiSr71L8oEShfwWQp5AKXkNXEWnZjUEFBPMpzYSLOs9pFicwPBEh7M+ibb8HBhRjlVjUblFcsVb6sz74ba+pT1uIbSw==,iv:S2wfidnHzQl7DiYiQGfexhh3oR64G9kXmb0VK7JWfc4=,tag:1unJu2F4pRXcb+XWRayfdg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:jyxGXACWQSRA5IwhVieglg==,iv:8XlsPY3HpftjOlLnSI/NFUAZZ87XBmlI1uSrwuJEmcs=,tag:q5sAFoYyrAGc3UP+Q9CwoQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:HyF0g5CQ7hsWYEvZQCoA7T+NgypF8dnZ0fzUCOAnpCIoS0yi2YAWTHPO/fPQhpuPGh3cooTU0d+mQzGy+okN3malGObWWNKkIKjjbXLh2BU8W+Wy+/DSBQ==,iv:uj5xL1T+lgCTPoZDKHO8NPl4BPiVaeTMlPbTnIOkC38=,tag:JuL+sE5CEnSGVKOuB0JZQQ==,type:str]
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WnhWMUNkU25TeUgzZzl2
            WkQwWlhWdUdxbXp2VWpoRVlhc01OODdKb1I4CmZvVG04TDhqRERrUzlzeFVaZVZU
            a29mNFFURTV5cFBiNlJKTUVHdDlubkUKLS0tIFZrNzNvb3dtVDNhOW5kOEVVWVZI
            Rmo0WGFVelFFb0pOTENjSFJpZUNzK0EKCEJq41cRxK4S4Tku0XT49wRYwdtYkbvi
            p0wr74HbvRO/R7nFaQ3Gfs4vT2F9BT4ezaoKcNG8g23sBQc92AOtsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T00:26:04Z"
    mac: ENC[AES256_GCM,data:+abTvBt/6jPCdgoGj3+MA+N5M232oitsalx8DJah3vIUWQ0Q/FvSNmxxSWpyRIYraJ0qFqIrON9v3UWwwtc+wEgpFdol7DABqDnt1Iijj6VYaUcEUdnVIhFjtdu5gwf7Jefn4XOMw+ofvIJgn7TcjR8SVKIDR1OEn/UVxHutUzs=,iv:Rc1+EesnQ1hMnaxdVu7NQHU7OkhGdxmXPtwDJPhiMB8=,tag:CDsJBuHHmZpZTq1G9fQerg==,type:str]
    version: 3.13.0
