apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      # Current version found here:
      # https://github.com/MoJo2600/pihole-kubernetes/blob/main/charts/pihole/Chart.yaml#L7
      version: 2.23.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/MoJo2600/pihole-kubernetes/blob/main/charts/pihole/values.yaml
  values:
    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: 10.0.0.202
      annotations:
        metallb.universe.tf/loadBalancerIPs: 10.0.0.202

    serviceDhcp:
      enabled: false

    serviceWeb:
      http:
        enabled: true
        port: 80
      https:
        enabled: false

    ingress:
      enabled: true
      ingressClassName: private
      path: /
      hosts:
        - pihole.hoam.lan

    virtualHost: pihole.hoam.lan
