---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runware-ui
  namespace: default
spec:
  selector:
    matchLabels:
      app: runware-ui
  template:
    metadata:
      labels:
        app: runware-ui
    spec:
      containers:
        - name: runware-ui
          image: ghcr.io/dbirks/runware-ui:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
          envFrom:
            - secretRef:
                name: runware-ui
---
apiVersion: v1
kind: Service
metadata:
  name: runware-ui
  namespace: default
spec:
  selector:
    app: runware-ui
  ports:
    - port: 80
      targetPort: 8080
