apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-webui
  namespace: default
spec:
  selector:
    matchLabels:
      app: stable-diffusion-webui
  template:
    metadata:
      labels:
        app: stable-diffusion-webui
    spec:
      runtimeClassName: nvidia
      containers:
        - name: stable-diffusion-webui
          image: ghcr.io/dbirks/sd-auto:72
          resources:
            limits:
              memory: 4Gi
              cpu: 2000m
---
apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-webui
  namespace: default
spec:
  selector:
    app: stable-diffusion-webui
  ports:
    - port: 80
      targetPort: 7860
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-diffusion-webui
  namespace: default
  labels:
    name: stable-diffusion-webui
spec:
  ingressClassName: private
  rules:
    - host: stable-diffusion-webui.birks.haus
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: stable-diffusion-webui
                port:
                  number: 80
