apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      # Current version found here:
      # todo, kinda sorta
      # https://pkgs.tailscale.com/unstable/helmcharts/index.yaml
      version: 1.81.191
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/deploy/chart/values.yaml
  # Reads from a secret called operator-oauth
  # values:
