apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      # Current version found here:
      # https://pkgs.tailscale.com/helmcharts/index.yaml
      version: 1.82.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/deploy/chart/values.yaml
  # Reads from a secret called operator-oauth
  # values:
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: home-subnet-connector
  namespace: default
spec:
  hostname: home-subnet-connector
  subnetRouter:
    advertiseRoutes:
      - "10.0.0.0/24"
