apiVersion: apps/v1
kind: Deployment
metadata:
  name: unms
  namespace: default
spec:
  selector:
    matchLabels:
      app: unms
  template:
    metadata:
      labels:
        app: unms
    spec:
      containers:
        - name: unms
          image: ubnt/unms:2.4.156
          env:
            - name: UNMS_PG_PASSWORD
              value: baddabing
            - name: UNMS_PG_USER
              value: unms
            - name: UNMS_PG_DB
              value: unms
            - name: UNMS_PG_SCHEMA
              value: unms
            - name: UNMS_PG_HOST
              value: unms-postgres
            - name: UNMS_PG_PORT
              value: "5432"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: unms
  namespace: default
spec:
  selector:
    app: unms
  ports:
  - port: 80
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unms
  namespace: default
  labels:
    name: unms
spec:
  ingressClassName: private
  rules:
  - host: unms.hoam.lan
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: unms
            port: 
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unms-postgres
  namespace: default
spec:
  selector:
    matchLabels:
      app: unms-postgres
  template:
    metadata:
      labels:
        app: unms-postgres
    spec:
      containers:
        - name: postgres
          image: ubnt/unms-postgres:2.4.156
          env:
            - name: UNMS_POSTGRES_PASSWORD
              value: baddabing
            - name: UNMS_POSTGRES_USER
              value: unms
            - name: UNMS_POSTGRES_DB
              value: unms
            - name: UNMS_POSTGRES_SCHEMA
              value: unms
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: unms-postgres
  namespace: default
spec:
  selector:
   name: unms-postgres
  ports:
  - port: 5432
    targetPort: 5432
