apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi-chart/unifi
      # Current version found here:
      # https://github.com/mkilchhofer/unifi-chart/blob/main/charts/unifi/Chart.yaml#L7
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: unifi-chart
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/mkilchhofer/unifi-chart/blob/main/charts/unifi/values.yaml
  values:
    ingress:
      enabled: true
      ingressClassName: private
      annotations: {}
      path: /
      hosts:
        - unifi.hoam.lan
    timezone: America/New_York
