apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      # Current version found here:
      # https://github.com/dirsigler/uptime-kuma-helm/blob/main/charts/uptime-kuma/Chart.yaml#L14
      version: 2.21.2
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/dirsigler/uptime-kuma-helm/blob/main/charts/uptime-kuma/values.yaml
  values:
    image:
      tag: 1.23.16-debian
    ingress:
      enabled: true
      className: private
      hosts:
        - host: uptime.hoam.lan
          paths:
            - path: /
              pathType: Prefix
    volume:
      enabled: true
      size: 5Gi
      storageClassName: nfs
