apiVersion: v1
data:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:GxeStpfVFiWt/1YlcnBx2i+lv0hz67AnRHBI203sZwgRZ7/qcA6F9bFK5sLh4KMvGHAjNA3aLYQiq0roaZuxXOjAHLs5cNX2A6URgWHA8y+bog218/QAJKzWxm0=,iv:I+0GxMbcogDxwjF24eD20h5GrFDsBxTBWCvvilOFHAQ=,tag:hdV9wr88wZ0C3gRFehLb6A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Siw8y4uBpg5WzmiNCXqZzIZPqbiPGOJygBI5BBAUXhJ5T20ukxlF7yWKmmc=,iv:B2GpYa1zrnXugFZMJbn8R5OFZPDE0ZdJJSwUFTMMBPY=,tag:CH4JqDQr2uAqx4D/h1AAng==,type:str]
kind: Secret
metadata:
    name: videogen-secrets
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVkpCVkRrbUs4TjRmTkt6
            VTFJMCtqYWdCbEhvYjRMMmxmZzhpWVM4eEJrCllzTDNMd28vY0NBWkkvMDhlb0Jl
            YzJIdFh4MUF2WGRHVVA0MXVZM1VIVncKLS0tIDk2dUhVdDlsd2F3NEtMRlRUTEtL
            b1E0NHJOUk5qVWN6bmxYanpWQ1JTL3MKRftAj8tT9s+nC7masQqCFuFIWRQshs5a
            evadtT6XEeL9AGIasMv9XqfLj3zktLGPzdrzYNB2h11SWtvpqByNig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T15:42:36Z"
    mac: ENC[AES256_GCM,data:wLG1ekpZcZyjU+PcmmKY6ZPvQucqzx1DjO5pJZFXfsctm/ryQwdrYA+qfk+zyCJtVoihbX0mZ/+ffl2/cO2L2SX2ikTxqQJgQ5xfGRrdOt3hpu5uz+ODjTBs5TC+i1BkjPK7aCV4xjUkD8qKUT/Ql9L2d1h0qK9g/HS7va7ZlW8=,iv:edsSrTKZsgUU2HFVdvD38Z8dmHRFYNKZiw1zovTpavw=,tag:NSjplTMyKV/WMuPhWTl1OQ==,type:str]
    version: 3.13.0
