apiVersion: v1
data:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:VQ9ZPPPBBytHc/XjIQ7gr/HdbufHr8Dq6RoyF7/ui9M+gAdsZRumFdomMGy6zoD8VaShIqdP1w71RajcxQQdiTdmwUPfkwOig6iieiOGMoYXPUoaisccMA==,iv:0oGsg4jqciJzF/xYp4wrhvBsWdVpLG51960UOabWR3A=,tag:ZkGnlxvnQ0IX6mArZrjh/g==,type:str]
kind: Secret
metadata:
    name: videogen-oidc
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbWpOcFNlelV5dlhLLzRW
            elE5Z0p3anE1SUZybVEyV0JXYmZTS3dzMEZrCjdPTnNTSGZJdStZcnBMTEdXS2NH
            K2FFNlNsbXBFTWFSbjBVc2FWSVpYb2MKLS0tICtWZkV0eUlIL2YyWEdMQS9TSXU0
            cjhoZy9SbWRrM3lSL1Z4T2Vsc0RSRWsK9wfwlxAt2nQNAX1HnCe2mleNu1WT2qwU
            NSjmAJI5E4My0oYAnGwYRmlgfmyCr+YCUJi0XgSbP0OJ3AqnSbBbkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wuzt6mcky73hyllpkwsegs7ryqph6ygc2q3esqhzsu8rfpgtyyqm3zr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T00:33:45Z"
    mac: ENC[AES256_GCM,data:/GFk6zYtOxA2/98kXRQsz5f1LFtU/OUG9bQi0GAWWCkF1XOcyqyQe98D9Nfd3lwh5OC774au4l2zMKfO+7ty5++lyo4pOnOmeCUbIh6g8rWABBHiVggB/IqfcVorMh6ieJELNCr1TpmLPMZLyvEfoh1xHxEyCUtwpMVWGdrOgiE=,iv:LTqwlC/BfFitIyye3fix4qPmeuHAD/DwMag/2ZwRErg=,tag:OuPTihdGSXUY0InMWeq5jQ==,type:str]
    version: 3.13.0
