apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vikunja
      # Current version found here:
      # https://github.com/truecharts/public/blob/master/charts/stable/vikunja/Chart.yaml#L42
      version: 17.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  # Default values:
  # https://github.com/truecharts/public/blob/master/charts/stable/vikunja/values.yaml
  values:
    # Disable Redis and CNPG (PostgreSQL) dependencies which may be causing credential issues
    cnpg:
      main:
        enabled: false
    redis:
      enabled: false

    vikunja:
      service:
        frontendurl: "http://vikunja.hoam.lan"

    # Configure persistence to use emptyDir instead of secret to avoid template issues
    persistence:
      vikunja-config:
        enabled: true
        type: emptyDir
      files:
        enabled: true
        type: emptyDir

    # Disable Traefik integrations to avoid CRD issues
    global:
      traefik:
        addServiceAnnotations: false
        commonMiddlewares: []

    ingressMiddlewares:
      traefik:
        tc-basic-secure-headers:
          enabled: false

    # Add ingress configuration
    ingress:
      main:
        enabled: true
        ingressClassName: private
        hosts:
          - host: vikunja.hoam.lan
            paths:
              - path: /
                pathType: Prefix

    metrics:
      main:
        enabled: false
