apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission
  name: transmission
  namespace: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - image: linuxserver/transmission
        name: transmission
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        ports:
        - containerPort: 9091
          name: webui
        volumeMounts:
        - mountPath: /downloads
          name: vol-downloads
      volumes:
      - name: vol-downloads
        nfs:
          server: 10.1.1.2
          path: /mnt/tetons/torrents
