apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmission-webui
  name: transmission-webui
  namespace: transmission
spec:
  ports:
  - name: "9091"
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: transmission-webui
  type: LoadBalancer
